/*
Problem 0002 - Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int main(void)
{
	int max = 4000000, sum, a, tmp, b = 1;
	sum = a = tmp = 0;
	
	while (b < max) {
		tmp = a;
		a = b;
		b += tmp;
		if (a % 2 == 0){
			sum += a;
		}
	}

	printf("%d\n", sum);

	return 0;
}

/* Output

4613732

*/